### ISSUE TITLE
Build Error DLPhotoPickerViewController.h file not found

### ISSUE THREAD

**Issue by tattoush** [darling0825/DLPhotoPicker#1]
Using swift 3 
I installed the pod
created my Header bridging file added
Import "DLphotoPicker.h"

build error: DLPhotoPickerViewController.h file not found

**Comment by darling0825** [comment]
Add  `"DLPhotoPicker.h"`  in  Header bridging file, not `"DLphotoPicker.h"`

```
#import "DLPhotoPicker.h"
```
