### ISSUE TITLE
Only works on simulator

### ISSUE THREAD

**Issue by puelocesar** [darling0825/DLPhotoPicker#2]
Images won't appear on my device (iPhone 5C on iOS 8.3). 

When trying to access the file at the URL provided by DLPhotoAsset, I get the following error:

`Error Domain=NSCocoaErrorDomain Code=260 "The file “IMG_4266.JPG” couldn’t be opened because there is no such file." UserInfo={NSFilePath=file:///var/mobile/Media/DCIM/104APPLE/IMG_4266.JPG, NSUnderlyingError=0x1701fb10 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

**Comment by darling0825** [comment]
@puelocesar Can you go to confirm that the picture(file:///var/mobile/Media/DCIM/104APPLE/IMG_4266.JPG) was deleted?

**Comment by puelocesar** [comment]
No, the image it's still there, and I can retrieve it with other libraries. 

Usually, in my code, I use [PHImageManager requestImageForAsset], and then save it on a tmp folder in order to use it. Can you point out how are you getting the photo url?

**Comment by darling0825** [comment]
@puelocesar You can view the file  "DLPhotoAsset.m" for detail. 

[[[DLPhotoManager sharedInstance] phCachingImageManager]
     requestImageDataForAsset:self.phAsset
     options:imageRequestOptions
     resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
        completion(info);
    }];

**Comment by darling0825** [comment]
@puelocesar You can view the photo in the disk with some tools. For example:
<img width="562" alt="2017-10-04 23 14 07" src="https://user-images.githubusercontent.com/5607604/31183672-d4f8bee6-a959-11e7-869d-c00760828d2a.png">

**Comment by puelocesar** [comment]
Yes, the photos are there, but Apple forbids you to access them directly. Here's the code I'm using to get them:

```
-(void)pickerController:(DLPhotoPickerViewController *)picker didFinishPickingAssets:(NSArray *)assets {
    
    NSMutableArray* results = [[NSMutableArray alloc] initWithCapacity:assets.count];
    
    for (DLPhotoAsset* dlAsset in assets) {
        
        PHAsset* asset = dlAsset.phAsset;
        
        PHImageRequestOptions * imageRequestOptions = [[PHImageRequestOptions alloc] init];
        imageRequestOptions.synchronous = YES;
        imageRequestOptions.deliveryMode = PHImageRequestOptionsResizeModeFast;
        
        [[PHImageManager defaultManager]requestImageForAsset:asset targetSize:CGSizeMake(1600,1600) contentMode:PHImageContentModeAspectFit options:imageRequestOptions resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info) {
            
            NSString* newFile = [NSString stringWithFormat:@"%@%@", NSTemporaryDirectory(), dlAsset.fileName];
            
            [UIImageJPEGRepresentation(result, 0.8) writeToFile:newFile atomically:true];
            
            [results addObject:newFile];
            
        }];
    }
    
    resolveBlock(results);
    
    [[UIApplication sharedApplication].keyWindow.rootViewController dismissViewControllerAnimated:true completion:nil];
}
```

**Comment by darling0825** [comment]
@puelocesar You can get image use method in DLPhotoAsset directly. Try again:

```
- (UIImage *)originImage;
- (NSData *)originImageData NS_AVAILABLE_IOS(8.0);
- (NSInteger)requestOriginImageWithCompletion:(void (^)(UIImage *image, NSDictionary *info))completion
                          withProgressHandler:(PHAssetImageProgressHandler)phProgressHandler;
- (NSInteger)requestOriginImageDataWithCompletion:(void (^)(NSData *, NSDictionary *))completion
                              withProgressHandler:(PHAssetImageProgressHandler)phProgressHandler NS_AVAILABLE_IOS(8.0);
```

**Comment by puelocesar** [comment]
Ok, thanks
